export interface ImaterialGridState {
    ID : number,
    InvoiceNo : number,
    CompanyName : string,
    Invoicedetails : string,
    CompanyCode : string,
    InvoiceAmount : number,
    BasicValue : number,
    Approver : any,
    IsApproved : boolean,
    Country : string,
    IsDeleted : boolean,
    headerCols : any,
    data : [],
}